[package]
name = "sudoku"
version = "0.1.0"
authors = ["LightDiscord <root@arnaud.sh>"]
edition = "2018"

[dependencies]
failure = "*"

[dependencies.arrayvec]
version = "*"
features = ["array-sizes-33-128"]